document.write("<div id=\"logo\">");
document.write("<div id=\"logo_text\">");
document.write("<!-- class=\"logo_colour\", allows you to change the colour of the text -->");
document.write("<h1><a href=\"index.html\">Guoxu Liu <span class=\"logo_colour\">(刘国旭)</span></a></h1>");
document.write("<h2>Nothing is impossible.</h2>");
document.write("</div>");
document.write("<div id=\"logo_badgePNU\" class=\"logo_badge\">");
document.write("<a href=\"http://www.pusan.ac.kr/eng/Main.do\"><img src=\"images/pnu.png\" title=\"Pusan National University\" height=\"120\"></a>");
document.write("</div>");
document.write("<div id=\"logo_badgeNTU\" class=\"logo_badge\">");
document.write("<a href=\"https://www.ntu.edu.sg/Pages/home.aspx\"><img src=\"images/ntu.png\" title=\"Nanyang Technological University\" height=\"120\"></a>");
document.write("</div>");
document.write("<div id=\"logo_badgeSDU\" class=\"logo_badge\">");
document.write("<a href=\"http://www.sdu.edu.cn\"><img src=\"images/sdu.png\" title=\"Shandong University\" height=\"120\"></a>");
document.write("</div>");
document.write("<div id=\"logo_badge\" class=\"logo_badge\">");
document.write("<a href=\"http://www.sdu.edu.cn\"><img src=\"images/blank\" title=\"\" height=\"120\"></a>");
document.write("</div>");
document.write("</div>");
